targets:
  $default:
    builders:
      audie_generator|audie_generator:
        enabled: true

builders:
  audie_generator:
    target: ":audie_generator"
    import: "package:audie_generator/builder.dart"
    builder_factories: ["builderFactory"]
    build_extensions: {".dart": [".audie_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
