name: audie_generator
version: 0.0.1
author: Edman Anjos <edmanjos@gmail.com>
description: Automatic dependency injection engine for Dart.
homepage: http://github.com/edman/audie

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  audie:
    path: ../audie
  source_gen: ^0.9.0
  analyzer: '>=0.33.3 <0.36.0'
  analyzer_plugin: '>=0.0.1-alpha.5 <0.0.1-alpha.8'
  build: ^1.0.0
  build_config: ^0.3.1
#  code_builder: ^3.0.0
  rxdart: ^0.23.1

dev_dependencies:
  build_test: ^0.10.3
  build_runner: ^1.0.0
  logging: ^0.11.0
  test: ^1.0.0
