name: example
version: 0.0.1
description: Compile-time dependency injection example using diversion.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  diversion:
    path: ../diversion

dev_dependencies:
  diversion_generator:
    path: ../diversion_generator
  build_runner: ^1.0.0

