name: example
version: 0.0.1
description: Compile-time dependency injection example using diversion.

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  built_collection: '>=2.0.0 <5.0.0'
#  built_value: '>=5.5.5 <7.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  diversion:
    path: ../

