name: example
version: 0.0.1
description: Compile-time dependency injection example using audie.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  audie:
    path: ../audie

dev_dependencies:
  audie_generator:
    path: ../audie_generator
  build_runner: ^1.0.0

