name: example
version: 0.0.1
description: Compile-time dependency injection example using diversion.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  # TODO: remove when you split annotations into a separate package
  diversion:
    path: ../

dev_dependencies:
  build_runner: ^1.0.0
  # TODO: uncomment later
  #diversion:
  #  path: ../

