targets:
  $default:
    builders:
      diversion|diversion:
        enabled: true

builders:
  diversion:
    target: ":diversion"
    import: "package:diversion/builder.dart"
    builder_factories: ["builderFactory"]
    build_extensions: {".dart": [".diversion.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
